### get transfers
GET http://localhost:8080/transfers

### get transfer
GET http://localhost:8080/transfers/2

### create transfer
POST http://localhost:8080/transfers/create
Content-Type: application/json

{
  "villainId": 1,
  "prisonId": 3,
  "reason": "bo czemu nie",
  "transferTime": 10
}